### ISSUE TITLE
Linked List problem.

### ISSUE THREAD

**Issue by pyaf** [ninjakx/Coding-practice#1]
I've got a bunch of dog breed names to store in a linked list type data structure. Use Cpp to solve the problem.

**Comment by ninjakx** [comment]
Done

**Comment by pyaf** [comment]
Talk is cheap, show me the code.

**Comment by ninjakx** [comment]
https://github.com/ninjakx/Coding-practice/blob/master/DS/linked_list(with_class_only).cpp

**Comment by pyaf** [comment]
good work
