### ISSUE TITLE
Binary Tree

### ISSUE THREAD

**Issue by pyaf** [ninjakx/Coding-practice#3]
Implement Binary tree using classes in cpp.

**Comment by ninjakx** [comment]
using array 
https://github.com/ninjakx/Coding-practice/blob/master/DS/binary_tree.cpp

**Comment by ninjakx** [comment]
Next quetion plz

**Comment by pyaf** [comment]
Use classes to implement the same.

**Comment by ninjakx** [comment]
Done

**Comment by pyaf** [comment]
Nope, not like this, even now you are using arrays (this time array of `mydata` objects). 
1. Don't use arrays.
2. `Node` is a better name than `mydata`.

**Comment by pyaf** [comment]
:roll_eyes: 
what has linkedlist got to do with binary tree? 
"Use classes to make a binary tree" is that not clear enough?

**Comment by ninjakx** [comment]
sorry I mean using the concept of pointers

**Comment by ninjakx** [comment]
https://github.com/ninjakx/Coding-practice/blob/master/DS/binary_tree_2.cpp

**Comment by pyaf** [comment]
learn how to clean up the code before the final push.

**Comment by pyaf** [comment]
It would have been better if you wrote a Binary tree class and a node class, adding nodes to the tree.
in your code, every node has two functions, they should be in binary tree class instead. learn how to write code which makes sense at first look.

**Comment by pyaf** [comment]
like:

class BinaryTree:
    functions: addNodeToLeft, addNodeToRight, DisplayTree, ...

class Node:
   attributes: data, left, right ...

like this.

**Comment by ninjakx** [comment]
https://github.com/ninjakx/Coding-practice/blob/master/DS/binary_2(modified).cpp

**Comment by ninjakx** [comment]
https://github.com/ninjakx/Coding-practice/blob/master/DS/binary_2_modified
