### ISSUE TITLE
Undirected Graph

### ISSUE THREAD

**Issue by pyaf** [ninjakx/Coding-practice#4]
Implement undirected graph in cpp using classes. Write clean and sensible code.

**Comment by ninjakx** [comment]
https://github.com/ninjakx/Coding-practice/blob/master/DS/undirected_graph.cpp

**Comment by pyaf** [comment]
Nicely coded, copied from somewhere? :thinking:

**Comment by ninjakx** [comment]
No created on my own. I know how to use vectors -_-

**Comment by pyaf** [comment]
another example of stupid naming of variables. 
```
class city
{   
    public:
    map<string,int> location;
   
}
```
Using one city object to store the map is nonsensical, though your code may work.

**Comment by pyaf** [comment]
your adjacency matrix itself can store map with the weights, an efficient way of approaching the problem. Map containing maps.

**Comment by ninjakx** [comment]
-_-
ab kya karna ismai

**Comment by ninjakx** [comment]
https://github.com/ninjakx/Coding-practice/blob/master/DS/city_graph_modified.cpp
